  # Find all the available rules by running:
  # swiftlint rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping
  - attributes
  - closure_end_indentation
  - closure_spacing
  - extension_access_modifier
  - first_where
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - notification_center_detachment
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - syntactic_sugar
  - vertical_parameter_alignment_on_call

disabled_rules: # rule identifiers to exclude from running
  - redundant_string_enum_value

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

force_cast: warning

attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@objc"]

force_try:
  severity: warning # explicitly

cyclomatic_complexity:
  warning: 10
  error: 50

line_length: 140

type_body_length:
  warning: 300
  error: 1000

file_length:
  warning: 500
  error: 1000

function_parameter_count:
  warning: 5
  error: 10

variable_name:
  max_length:
    warning: 40
    error: 60
  min_length:
    warning: 1

nesting:
  type_level:
    warning: 2
    error: 5
  statement_level:
    warning: 3
    error: 5