// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import Foundation
import Rswift
import UIKit

struct R: Rswift.Validatable {
  static func validate() throws {
    try intern.validate()
  }
  
  struct file {
    
  }
  
  struct font {
    
  }
  
  struct image {
    static let icon_checkmark = ImageResource(bundle: _R.hostingBundle, name: "icon_checkmark")
    static let launchImage = ImageResource(bundle: _R.hostingBundle, name: "LaunchImage")
    
    static func icon_checkmark(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_checkmark, compatibleWithTraitCollection: traitCollection)
    }
    
    static func launchImage(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.launchImage, compatibleWithTraitCollection: traitCollection)
    }
  }
  
  private struct intern: Rswift.Validatable {
    static func validate() throws {
      try _R.validate()
    }
  }
  
  struct nib {
    
  }
  
  struct reuseIdentifier {
    static let recordListCell: ReuseIdentifier<UITableViewCell> = ReuseIdentifier(identifier: "RecordListCell")
  }
  
  struct segue {
    struct recordDetailViewController {
      static let unwindToRecordList: StoryboardSegueIdentifier<UIStoryboardSegue, RecordDetailViewController, UIViewController> = StoryboardSegueIdentifier(identifier: "unwindToRecordList")
      
      static func unwindToRecordList(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, RecordDetailViewController, UIViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.recordDetailViewController.unwindToRecordList, segue: segue)
      }
    }
    
    struct recordListViewController {
      static let showRecordDetailViewController: StoryboardSegueIdentifier<UIStoryboardSegue, RecordListViewController, RecordDetailViewController> = StoryboardSegueIdentifier(identifier: "showRecordDetailViewController")
      
      static func showRecordDetailViewController(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, RecordListViewController, RecordDetailViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.recordListViewController.showRecordDetailViewController, segue: segue)
      }
    }
  }
  
  struct storyboard {
    static let main = _R.storyboard.main()
    
    static func main(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.main)
    }
  }
}

struct _R: Rswift.Validatable {
  static let hostingBundle = NSBundle(identifier: "com.blackjacx.gazz")
  
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct main: StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UINavigationController
      
      let bundle = _R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if UIImage(named: "icon_checkmark") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_checkmark' is used in storyboard 'Main', but couldn't be loaded.") }
      }
    }
  }
}