# Fastlane Documentation:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
#
# Fastlane actions: 
# https://docs.fastlane.tools/actions/
#
# Bitrise with fastlane example:
# https://github.com/bitrise-samples/fastlane/blob/master/BitriseFastlaneSample/fastlane/Fastfile
#
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
#
#
# This file was created by the help of https://gist.github.com/ulhas/e8e529d08849b8cda947
#
#
# NOTE: To use faslane first do:
#           gem install bundler && bundle install
#
#       and then run:
#           bundle exec fastlane release product_name:Gasoline version:"1.0.0" github_account:"blackjacx"
#           bundle exec fastlane test product_name:Gasoline
#
# Configure the following environment variables for your project 
# on your CI and in fastlane/.env:
#
# ENV["SLACK_URL"] = "..."
# ENV["GITHUB_TOKEN"] = "..."




# TODO: Deploy app to Apple TestFlight





# This is the minimum version number required. 
# Update this, if you use features of a newer version.
fastlane_version "2.45.0"

default_platform :ios



before_all do
  cocoapods(use_bundle_exec: true)
end


after_all do |lane|
  # This block is called, only if the executed lane was successful
  notification(
  	subtitle: "Success", 
  	message: "Lane #{lane} completed successfully"
  )
  slack(success: true, message: "*Successfully deployed new update.*")
end


error do |lane, exception|
  # This block is called, only if the executed lane failed
  notification(
  	subtitle: "Failure",
  	message: "Lane #{lane} failed with error #{exception.message}"
  )
  slack(success: false, message: "*#{exception.message}*")
end

###############################################################################
#                          PUBLIC SECTION
###############################################################################

lane :feature_test do |options|

end




desc "Releases a new product version"
lane :release do |options|

  if !options[:product_name] || !options[:version] || !options[:github_account]
    raise "No product_name, version specified, or github_account specified!".red
  end

  product_name = options[:product_name]
  version = options[:version]
  github_account = options[:github_account]
  project = "#{product_name}.xcodeproj"
 
  ensure_git_status_clean(show_uncommitted_changes: true)
  ensure_git_branch(branch: "develop")
  git_pull

  test(product_name: product_name, run_danger: true)

  # Increments CFBundleVersion by one and sets CFBundleShortVersionString
  increment_version_number(xcodeproj: project, version_number: version)
  increment_build_number(xcodeproj: project)

  # read changelog
  changelog = read_changelog

  # stamp unreleased section with released version
  stamp_changelog(section_identifier: version)

  sh "git commit -am 'Fastlane: Release on Production #{version}'"
  sh "git checkout master && git merge develop"

  add_git_tag(tag: version)

  # push all changes on all branches and all tags
  push_to_git_remote(local_branch: "master", remote_branch: "master")
  push_to_git_remote(local_branch: "develop", remote_branch: "develop")

  push_github_release(
  	product_name: product_name, 
  	version: version, 
  	github_account: github_account, 
  	changelog: changelog
  ) 

  # deploy to TestFlight, Crashlytics, Hockey or whatever
end




desc "Runs tests optionally with danger"
lane :test do |options|

  if !options[:product_name]
    raise "No product_name or use_ci specified".red
  end

  product_name = options[:product_name]
  run_danger = options[:run_danger]

  # Easily run tests of your iOS app using scan
  scan(
    workspace: "#{product_name}.xcworkspace",
    scheme: product_name,
    clean: true,
    devices: ["iPhone 7"],
    skip_build: true,
    thread_sanitizer: true,
    output_types: "html"
  )

  # Runs danger for the project
  if run_danger

    danger(
      use_bundle_exec: true,
      github_api_token: ENV["GITHUB_TOKEN"],
      verbose: true
    )
  end

end




###############################################################################
#                          PRIVATE SECTION
###############################################################################

desc "Creates a github release with a git commit changelog"
private_lane :push_github_release do |options|

  if !options[:product_name] || !options[:version] || !options[:github_account] || !options[:changelog]
    raise "No product_name, version specified, github_account or changelog specified!".red
  end

  product_name = options[:product_name]
  version = options[:version]
  github_account = options[:github_account]
  changelog = options[:changelog]

  github_release = set_github_release(
    repository_name: "#{github_account}/#{product_name}",
    api_token: ENV["GITHUB_TOKEN"],
    name: version,
    tag_name: version,
    description: ("#{changelog}" rescue "No changelog provided"),
    commitish: "master"
  )
end
